"""Render a dependency-free static download/research site from measured artifacts."""
import csv
from datetime import datetime, timezone
import html
import json
import re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];DOCS=ROOT/'docs'
M=json.loads((DOCS/'downloads/manifest.json').read_text())
A=json.loads((DOCS/'downloads/structural-audit.json').read_text())
CV=json.loads((DOCS/'downloads/holdout.json').read_text())
FEED=json.loads((DOCS/'source-feed.json').read_text())
H41E=json.loads((ROOT/'research/experiments/h41e-kinematic-holdout.json').read_text())
ALT=json.loads((DOCS/'evidence/h41a_raster_build_receipt.json').read_text())
ALT_HOLDOUT=ALT['holdout']
ALT_DOWNLOAD='downloads/'+Path(ALT['output']['path']).name
ALT_UNSUPPORTED_FOLDS=sum(
    fold.get('per_arm',{}).get('h41a_full',{}).get('status') != 'scored'
    for fold in ALT_HOLDOUT.get('fold_results',[])
)
E=html.escape
BUILD_DATE=datetime.now(timezone.utc).strftime('%d %B %Y')
HISTORICAL=FEED['competition_leaderboard']['last_recorded_public_observation']
REPO='https://github.com/buffedlizard55-lab/GEMSDOE41'
PROBLEM='https://www.drivendata.org/competitions/306/competition-doe-gems/page/967/'
LEADER='https://www.drivendata.org/competitions/306/competition-doe-gems/leaderboard/'
DOWNLOAD='downloads/'+M['filename']
H42=M['h42']
H42P=H42['artifacts'][H42['primary']]
H42PF=Path(H42P['checks']['path']).name
DOWNLOAD_H42='downloads/'+H42PF
DOWNLOAD_H42_ZIP='downloads/'+H42PF.replace('.tif','.zip')
DOWNLOAD_H42_CHECKS='downloads/'+H42PF+'.checks.json'
H42DKEY='h42d-statemap-lattice-37k'
H42D=H42['artifacts'].get(H42DKEY)
H42DF=Path(H42D['checks']['path']).name if H42D else ''
HO42=json.loads((ROOT/'evidence/h42_holdout.json').read_text())
AGG42=HO42['aggregated']
ENR42=json.loads((ROOT/'evidence/h42_enrichment.json').read_text())
UNI42=json.loads((ROOT/'evidence/h42_uniqueness.json').read_text())
def _enr_rows():
    out=[]
    for art,e in ENR42['results'].items():
        for mk,v in (e.get('markers') or {}).items():
            out.append([art,mk,f"{v['enrichment']:.3f}×",f"p={v['p_value']:.3f}",
                        'PASS' if v['passes'] else 'fail'])
    return out
H42_ENR_ROWS=_enr_rows()
def _uni_max(art):
    r=UNI42.get(art) or {}
    return max((v['jaccard'] for v in r.values()), default=0.0) if r else 0.0
H42_UNI_MAX=max(_uni_max(a) for a in UNI42) if UNI42 else 0.0
def _art_card(nm,art,role):
    fn=Path(art['checks']['path']).name
    return (f'<div class="card"><span class="pill">{role}</span><h3><code>{E(fn)}</code></h3>'
            f'<p>{art["emitted_px"]:,} positive cells (budget {art["requested_budget"]:,}; support-limited shortfall {art["support_shortfall"]:,}). '
            f'Tracking name <code>{E(art["tracking_name"])}</code>. '
            f'SHA-256 bytes <code>{art["checks"]["sha256_bytes"][:16]}…</code> · pixels <code>{art["checks"]["sha256_pixels"][:16]}…</code>. '
            f'Checks on re-opened bytes: <strong>{"PASS" if art["checks"]["all_pass"] else "FAIL"}</strong>.</p>'
            f'<p><a class="button primary" href="downloads/{E(fn)}" download>↓ .tif</a> '
            f'<a href="downloads/{E(fn).replace(".tif", ".zip")}" download>.zip</a> '
            f'<a href="downloads/{E(fn)}.checks.json">checks.json</a></p></div>')
H42_CARDS=_art_card('primary',H42P,'Primary · brief-compliant')+(_art_card('secondary',H42D,'Secondary · state-map residual') if H42D else '')
JA42=H42P['junction_audit']['junction_concentration']
H42_CPM={k:(AGG42.get(k) or {}).get('mean_cpm_ladder',0.0) for k in AGG42}
H42_GATE_ROWS=[
 ['Blocked-holdout promotion','arm a or b beats density/evidence/random in \u22653 of 4 folds',
  f"FAIL \u2014 0/4 folds; junction arm {H42_CPM.get('h42b_junction_prior',0):.4f} cpm vs evidence control {H42_CPM.get('control_evidence',0):.4f}"],
 ['Label-free enrichment','beats 500 stratified nulls by \u00d71.2 with p<0.05',
  "FAIL \u2014 every marker between 0.294\u00d7 and 0.895\u00d7, all p \u2265 0.89"],
 ['Uniqueness vs family','no byte-equality with any shipped raster of the project family',
  f"PASS \u2014 max Jaccard {H42_UNI_MAX:.4f}; a prior submission cannot be rebuilt here by construction"],
 ['Format','single-band float32 \u00b7 values in [0, 1] \u00b7 template grid \u00b7 0 cells \u2264200 m from the catalogue',
  'PASS \u2014 verified on re-opened delivered bytes (checks.json receipts)'],
]

def page(title,body):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="An auditable Walker Lane structural-transfer hypothesis for the DOE GEMS Prize. New GeoTIFF, reproducible evidence, honest validation."><title>{E(title)} · GEMSDOE41</title><link rel="stylesheet" href="style.css"></head><body>
<header><div class="nav"><a class="brand" href="index.html">GEMS<span> / </span>41</a><nav aria-label="Main"><a href="index.html">Overview</a><a href="executive-summary.html">Submission guide</a><a href="research.html">Research &amp; tests</a><a href="sources.html">Evidence</a><a href="h41/index.html">Kinematic ranking ↗</a><a href="{REPO}">Repository ↗</a></nav></div></header><main>{body}</main>
<footer class="footer"><span>Maximize P(Win). Own the Outcome.<br>Reproducible science. No unsupported score promises.</span><span>DOE GEMS research • Built {BUILD_DATE}<br>AI-assisted research and code; no synthetic measurement data.</span></footer><script src="site.js" defer></script></body></html>'''

def download_block():
    return f'''<div class="actions"><a class="button primary" href="{DOWNLOAD_H42}" download>↓ Download candidate GeoTIFF (.tif)</a><a class="button" href="{DOWNLOAD_H42_ZIP}" download>.zip</a><a href="{DOWNLOAD_H42_CHECKS}">Checks receipt ↗</a><a href="downloads/format-receipt.json">H41-era format receipt ↗</a></div><p class="fine">Unique name <code>{E(H42['submission_name'])}</code> · one band · float32 · EPSG:32611 · 100 m · 3292 × 3730 · every stored value exactly 0.0 or 1.0 — in [0, 1] by construction · {H42P['emitted_px']:,} positive cells · 0 cells ≤200 m from the published catalogue</p>'''

def table(headers,rows):
    return '<div class="table-wrap"><table><thead><tr>'+''.join('<th>'+x+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(x)+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'

HISTORICAL_ROWS = [row for row in HISTORICAL.get('observed_rows', []) if row.get('rank') in (1, 2, 3, 4, 13)]
HISTORICAL_TABLE = table(
    ['Rank', 'Participant shown in dated snapshot', 'Public DTI'],
    [[f"#{row['rank']}", E(str(row['participant'])), f"{row['score']:.4f}"] for row in HISTORICAL_ROWS],
)


def source_feed_fallback():
    last=HISTORICAL.get('observed_date_utc','unknown');score=HISTORICAL.get('score')
    historic=(f" Last recorded public leaderboard observation: {score:.4f} on {E(last)} (historical only; not current)." if isinstance(score,(int,float)) else '')
    return ("Daily permitted official-source health is loaded from this site's same-origin JSON snapshot. "
            "DrivenData leaderboard monitoring is disabled by its Terms of Use; current standings are unknown."
            f"{historic} ")

home=f'''<section class="hero"><div><span class="eyebrow">FIELD EXPERIMENT 42 / WALKER LANE BIMODAL</span><h1>Follow the transfer.<br>Test the hypothesis.</h1><p class="lead">A new junction-proximity dot lattice, generated against the bimodal structural prompt: catalogue geometry and local orientation only—no new geophysics transforms, and no previous submission of this project family.</p><span class="pill warn">Research candidate · both preregistered gates failed · no slot spent</span>{download_block()}<p class="fine">Built and validated 2026-10-06 in-session under a preregistered protocol; three independent builds produced byte-identical rasters. Not organizer-scored. Download, inspect, and decide; do not spend a weekly slot on it.</p></div><div class="map-card"><img src="structural-map.png" alt="Study-area map showing mapped faults in gray and new transfer-corridor confidence in color"><div class="caption">01 / Structural position, not catalogue density. <a href="structural-map.png">Open map ↗</a></div></div></section>
<div class="stats"><div class="stat"><b>{H42P['emitted_px']:,}</b><span>Positive cells in the H42 primary artifact</span></div><div class="stat"><b>{100*JA42['frac_within_3px_of_corridor']:.1f}%</b><span>Cells within 3 px of a junction corridor</span></div><div class="stat"><b>{100*JA42['frac_in_neither_population']:.1f}%</b><span>Cells on open ground in neither mapped population</span></div><div class="stat"><b>0</b><span>Predicted pixels ≤200 m from catalogue</span></div></div>
<section class="section split"><div><span class="eyebrow">THE RESULT, WITHOUT THE SPIN</span><h2>Valid file.<br>Unproven discovery.</h2><p>Both H42 artifacts pass the format, uniqueness-versus-every-shipped-raster, and junction-concentration checks. They do <strong>not</strong> pass the preregistered promotion gates, so no slot is recommended: the arms beat density/evidence/random in 0 of 4 folds, and the label-free enrichment test fails against stratified nulls.</p><a href="research.html#h42">Read the complete preregistered experiment →</a></div><div class="card"><span class="pill warn">HOLDOUT / DO NOT SUBMIT YET</span><h3>Arms win 0 of 4 folds</h3><p>Measured ladder-mean credit-per-mass on H42-HO (withheld state-map traces, 3 px isolation guard): junction arm <code>{H42_CPM.get('h42b_junction_prior', 0):.4f}</code> vs evidence control <code>{H42_CPM.get('control_evidence', 0):.4f}</code>, random <code>{H42_CPM.get('control_random', 0):.4f}</code>, density <code>{H42_CPM.get('control_density', 0):.4f}</code>. Junction concentration is a design check, not independent discovery evidence.</p><p class="fine">A line-anchored prior is un-evaluable under this instrument's guard by construction (prereg Part 5); it was recorded as a failure and not re-tuned away. No score-comparison claim is justified: 0.2778 is user-reported, and current leaderboard standings are unknown.</p></div></section>
<section class="section"><span class="eyebrow">TWO GEOMETRIC CRITERIA</span><h2>From fault traces to a falsifiable prediction.</h2><div class="three"><article class="card"><span class="num">01</span><h3>Separate the populations</h3><p>Assign axial strike to NW or N/NNE geometry. Retain every classification, including ambiguous and source-slip-discordant traces.</p></article><article class="card"><span class="num">02</span><h3>Connect genuine endpoints</h3><p>Find the nearest N/NNE receiver within 5 km of an outward-facing NW endpoint. Reject connected fragments and boundary tips.</p></article><article class="card"><span class="num">03</span><h3>Check local orientation</h3><p>Compare a topographic tangent proxy with the geometrically closer population. No new magnetic, gravity, thermal, or conductivity transform.</p></article></div></section>
<section class="section card"><div class="split"><div><span class="eyebrow">DOWNLOAD &amp; REPRODUCE</span><h2>One artifact. A complete audit trail.</h2><p>The static site serves the precomputed, verified model output. It does not claim to train a model in your browser.</p><a href="executive-summary.html">Submission instructions →</a></div><div><p><a href="downloads/classified-traces.csv">Every trace classification (CSV)</a><br><a href="downloads/corridors-utm11.geojson">Transfer corridors (projected GeoJSON)</a><br><a href="downloads/structural-audit.json">Junction &amp; novelty diagnostics</a><br><a href="downloads/holdout.json">Every validation fold</a><br><a href="{REPO}/actions/workflows/reproduce.yml">Rebuild pipeline on GitHub Actions</a></p></div></div></section>
<section class="section" id="h42-artifacts"><span class="eyebrow">CURRENT CANDIDATES · H42 · 2026-10-06</span><h2>Two lattice artifacts. One click each. Research-grade.</h2>
<p>The protocol and five hypotheses were preregistered in <a href="{REPO}/blob/main/research/hypotheses-h42.md">research/hypotheses-h42.md</a> <em>before</em> implementation; the one protocol amendment (A1, line-anchored arms measured with a 2 px kernel) was recorded before its corrected results were seen. Three independent builds produced byte-identical rasters.</p>
<div class="two">{H42_CARDS}</div>
{table(['gate','criterion','measured'],H42_GATE_ROWS)}
<p class="fine">Decision, verbatim
<p class="fine">Decision, verbatim from the manifest: {E(H42['decisions']['slot_recommendation'])}</p></section>
<section class="section card"><div class="split"><div><span class="eyebrow">SUPPLEMENTAL IMPLEMENTATION · H41-A-R</span><h2>A distinct raster-derived variant.</h2><p>H41-A-R is the separate raster-based implementation preserved from PR #8; it is not the source-vector H41-A featured above. Its registered four-quadrant test found no eligible candidate support in {ALT_UNSUPPORTED_FOLDS}/4 interiors, so its DTI is null/unevaluable—not zero—and it is not slot-eligible.</p><p><strong>Unique tracking name:</strong> <code>{E(ALT['submission_name'])}</code><br><strong>SHA-256:</strong> <code>{ALT['output']['sha256']}</code></p></div><div><p><a class="button" href="{ALT_DOWNLOAD}" download>↓ Download H41-A-R research GeoTIFF</a></p><p><a href="h41a-raster-variant.html">Method, limitations, and evidence →</a><br><a href="h41a-raster-submission-guide.html">Variant-specific upload guide →</a></p><p class="fine">Download is for research/inspection only. Do not spend a submission slot until a candidate beats the locked spatial holdout best.</p></div></div></section>
<section class="section" id="live-feed"><div class="section-head"><div><span class="eyebrow">LIVE OFFICIAL DATA</span><h2>Recent USGS ComCat events</h2></div><p>A browser-fetched 30-day snapshot of magnitude ≥1 events near the study area. Seismicity is context only—not proof of a fault, geothermal resource, or candidate truth.</p></div><div class="card"><p id="comcat-status" aria-live="polite">Loading the live USGS event feed…</p><ul id="comcat-events"><li>Waiting for the official endpoint.</li></ul><p><a id="comcat-query" href="https://earthquake.usgs.gov/fdsnws/event/1/">Open the USGS ComCat query ↗</a></p><p class="fine">This feed contacts USGS ComCat directly. It never polls DrivenData or its leaderboard. If browser access is blocked, use the linked official query.</p></div></section>
<div class="feed" id="source-feed" aria-live="polite">{source_feed_fallback()}<a href="{LEADER}">Open official leaderboard ↗</a> · <a href="https://www.drivendata.org/termsofuse/">Terms of Use ↗</a> · <a href="source-feed.json">Inspect source snapshot ↗</a></div>'''
(DOCS/'index.html').write_text(page('Structural transfer, honestly tested',home))

executive=f'''<div class="prose"><span class="eyebrow">EXECUTIVE SUMMARY / SUBMISSION GUIDE</span><h1>Your GeoTIFF, ready to inspect.</h1><p class="lead">The file has been generated and independently re-opened. Download it directly—no conversion, editing, or model training is required.</p>{download_block()}<div class="notice"><strong>Do not submit this candidate yet.</strong><p>The H42 primary failed both preregistered promotion gates on the blocked instrument (arms win 0/4 folds; label-free enrichment fails against 500 stratified nulls), and a clean historical-best comparison remains unavailable. Format-valid does not mean scientifically validated or competitive. No weekly slot has been spent.</p></div><p>H41-E, the preregistered follow-on test, also failed to improve the fixed holdout. <a href="research.html#follow-on">Read its result and the remaining ranked hypotheses →</a></p>
<h2>Artifact identity — current H42 candidate</h2><p><strong>Filename</strong><br><code>{H42PF}</code> (also as <code>{H42PF.replace('.tif','.zip')}</code>)</p><p><strong>Unique submission name</strong><br><code>{E(H42['submission_name'])}</code></p><p><strong>Short note ({len(H42['note'])} characters)</strong></p><div class="copybox"><code id="submission-note">{E(H42['note'])}</code><button class="copy" data-copy="submission-note" type="button">Copy note</button></div><p class="fine">SHA-256 of delivered bytes: <code>{H42P['checks']['sha256_bytes']}</code> · pixel array: <code>{H42P['checks']['sha256_pixels']}</code> · {H42P['emitted_px']:,} positive cells</p><p class="fine">Secondary research artifact: <code>{H42DF}</code> ({H42D['emitted_px']:,} cells; same format class; state-map residual lattice). The prior H41-era candidate <code>{M['filename']}</code> is superseded on this page; its receipts remain in the manifest.</p>
<section class="section"><h2>When a future candidate clears the gate</h2><ol><li>Review its <strong>clean, spatially blocked comparison</strong> against the current best. Require an improvement before spending one of the three weekly slots.</li><li>Download the single <code>.tif</code> using the button above. Do not upload the map PNG, HTML page, audit JSON, or a renamed document.</li><li>Sign in to <a href="https://www.drivendata.org/competitions/306/competition-doe-gems/">DrivenData’s GEMS competition</a>, confirm eligibility and accept the official rules using your own account.</li><li>Open <strong>New submission</strong>. Under <strong>File to submit</strong>, choose the downloaded GeoTIFF. Use the unique name in your internal tracker and paste the short note into <strong>Note (optional)</strong>.</li><li>Submit only after the gate passes. Wait for the portal’s validation and score. Record the exact file hash, submission ID, note, and organizer-reported score. A local validator cannot guarantee portal acceptance.</li><li>Select one final submission for both prize rounds by the official deadline. Disclose AI assistance in the required narrative; eligibility and certifications must be completed by the participant.</li></ol><p>These steps follow the <a href="{PROBLEM}#submission-format">format specification</a> and <a href="https://docs.nlr.gov/docs/fy26osti/96647.pdf">official rules, §§3.2–3.5</a>.</p></section>
<section class="section"><h2>Why this file avoids the range error</h2><p>Every one of the 12,279,160 stored values of each H42 artifact is finite and exactly 0.0 or 1.0: no NaN, no nodata tag, no internal mask, and zeros outside the footprint. The value set is literally {{0, 1}}, so a “Predicted values must be in range [0, 1]” rejection is impossible by construction on these bytes. Verified by re-opening the delivered files (<code>checks.json</code>: binary values, min 0.0, max 1.0, shape 3730 × 3292, transform identical to the template, 0 positive cells within 200 m of the published catalogue).</p><p>The exact cause of your earlier portal error is unknown without the rejected bytes. Out-of-range sentinel values are one possible cause; NaN alone is not proven to be the cause. We verified the current file rather than guessing about the old one.</p></section>
<section class="section"><h2>Rebuild rather than copy</h2><pre><code>bash scripts/download_competition_data.sh
.venv/bin/python scripts/prepare_data.py
.venv/bin/python scripts/run_pipeline.py
.venv/bin/python scripts/build_site.py</code></pre><p><a href="{REPO}/actions/workflows/reproduce.yml">Run the reproducibility workflow</a> or use the setup commands in the README. The geometry-only model is CPU-based; it does not require a GPU. Rebuilding identical inputs reproduces the same scientific hypothesis, not an artificial “new” submission made by renaming it. Cross-run pixel values are audited to an absolute tolerance of 64 float32 epsilons (about 0.00000763); the exact grid, valid mask, and outside-footprint encoding must also match. Exact file hashes still identify the specific delivered bytes.</p></section>
<section class="section"><h2>Supplemental raster-derived variant (not this guide’s primary file)</h2><p>The repository also preserves <strong>H41-A-R</strong>, a distinct raster-input implementation from PR #8. It is separate from the main source-vector H41-A above. H41-A-R has no eligible support in {ALT_UNSUPPORTED_FOLDS}/4 held-out interiors; its candidate DTI is null/unevaluable and its slot gate is closed. <a href="h41a-raster-variant.html">Review its evidence</a> or <a href="{ALT_DOWNLOAD}" download>download that research GeoTIFF</a>. Do not submit either candidate unless the relevant spatially blocked promotion gate is passed.</p></section></div>'''
(DOCS/'executive-summary.html').write_text(page('Executive summary & submission',executive))

foldrows=[[f['fold'],f['anchor_parts'],f['corridors'],f"{f['prediction_mass']:.8f}",f"{f['metrics']['candidate']['dti']:.6e}",f"{f['metrics']['geometry_only']['dti']:.6e}"] for f in CV['folds']]
research=f'''<div class="prose"><span class="eyebrow">RESEARCH NOTE / H41-A</span><h1>A structural hypothesis.<br>Not a score promise.</h1><p class="lead">The target is missing geological faults indicative of geothermal resources—not verified geothermal vents, reservoirs, or drill-ready prospects.</p>
<section class="section" id="h42"><span class="eyebrow">H42 · PREREGISTERED · MEASURED · GATES FAILED</span><h2>Five hypotheses, one frozen instrument, an honest negative.</h2>
<p>Written before implementation in <a href="{REPO}/blob/main/research/hypotheses-h42.md">research/hypotheses-h42.md</a>: Part 1 evidence review of the family history; Part 2 the registered slate (H42-A official-vector residual recall — falsified by receipt before any modeling; H42-B junction dot lattice; H42-C corroboration-intersection variant; H42-D state-map residual lattice; H42-E 1 m DEM LoG, deferred); Part 3 the fixed H42-HO protocol (4 folds of withheld SGMC residual traces, 3 px isolation guard, 2.5k/5k/10k/20k budget ladder, arms must beat density/evidence/random in ≥3 folds); Part 5 amendment A1 (2 px kernel for line-anchored arms; verdict must test the arms against controls, not the table winner) recorded before corrected results were seen.</p>
{table(['field on H42-HO','ladder-mean credit per mass','reading'],[
 ['h42b junction arm (shipped primary)', f"{H42_CPM.get('h42b_junction_prior',0):.4f}", 'wins 0/4 folds vs all controls — holdout FAIL'],
 ['h42d state-map arm', f"{H42_CPM.get('h42d_state_prior',0):.4f}", 'line-anchored fields have zero support inside the guarded scored domain; un-evaluable, recorded as failure, not re-tuned'],
 ['control: scarp evidence', f"{H42_CPM.get('control_evidence',0):.4f}", 'tops the instrument; 3.1× random — the most useful open-ground predictor measured'],
 ['control: random dots', f"{H42_CPM.get('control_random',0):.4f}", 'beats density: spread coverage beats line-following for unknown faults'],
 ['control: catalogue density', f"{H42_CPM.get('control_density',0):.4f}", '—'],
 ['control: raw residual', f"{H42_CPM.get('control_residual',0):.4f}", 'confirms the guard’s structural zero'],
])}
<p>Enrichment gate (500 stratified circle nulls; pass needs ≥1.2× and p&lt;0.05): {table(['artifact','marker','enrichment','p','verdict'],H42_ENR_ROWS)}</p>
<p class="fine">Uniqueness ledger: max Jaccard {H42_UNI_MAX:.4f} against every shipped raster of the project family; byte-equality with any prior submission refused by construction. Full receipts: <a href="{REPO}/blob/main/evidence/h42_holdout.json">holdout</a> · <a href="{REPO}/blob/main/evidence/h42_enrichment.json">enrichment</a> · <a href="{REPO}/blob/main/evidence/h42_uniqueness.json">uniqueness</a> · <a href="{REPO}/blob/main/evidence/h42_source_audit.json">input digests (all MATCH)</a>.</p>
<p class="fine">Next registered idea (NOT built, NOT claimed): open-ground evidence×orientation lattice (H42-F). It must not be tuned on this instrument; a new preregistration and a guard-appropriate test are prerequisites.</p></section>
<section class="section" id="h33-score-audit"><h2>H33 score attribution and dated public leaderboard snapshot</h2><p><strong>Historical observation only (2026-10-05 UTC):</strong> the public page showed 0.3262 at rank 1, 0.3195 at rank 4, and 0.2778 at rank 13 for participant <code>extradr19</code>. Those are participant rows, not file receipts. Current standings are unknown; this project does not monitor the leaderboard.</p>{HISTORICAL_TABLE}<p>The supplied experiment list reports the H33-2-B2 filename at 0.2778, but no organizer receipt links that filename or its hash to the rank-13 participant. GEMSDOE32’s own page labels its H33 artifact <code>UNSCORED</code>. The filename-to-score mapping remains user-reported, not authenticated. <a href="{REPO}/blob/main/research/h33-score-analysis.md">Read the full source and attribution audit ↗</a> · <a href="{LEADER}">Official page, for reference ↗</a> · <a href="https://www.drivendata.org/termsofuse/">Terms of Use ↗</a></p><p><strong>Why a 0.2778 result is plausible:</strong> GEMSDOE32 H33-2-B2 contains 37,654 binary dots; its owner-authored method removes 2,545 pixels (6.33%) within 200 m of the catalogue from a 40,199-dot base reported at 0.2708. This is post-hoc sparsification of an existing detector, not a new geological detector. The official metric rewards maximum kernel-weighted prediction at truth pixels; nearby redundant dots may add false-positive mass without adding coverage, so pruning can improve a proxy ratio, while also deleting predictions for real adjacent faults.</p><p><strong>Can we score higher?</strong> Possibly, but neither the owner-reported H33 score mapping nor this experiment establishes that we can. The 17.4% numerical gap between the 0.2778 filename claim and the 0.3262 rank-1 public row in the dated snapshot is not an authenticated model improvement, and neither value is current. Hidden labels, a filename receipt, and clean historical-best OOF predictions are unavailable.</p></section>
<section class="section"><h2>Four candidates, ranked before implementation</h2>{table(['Rank','Hypothesis and layers','Missing-fault mechanism / novelty','Cost & expected utility'],[
['1 · implemented','H41-A: official faults + detrended elevation tangent','Unlike-family endpoint→nearest-receiver corridors; new field rather than H33 pruning','Moderate; highest qualitative plausibility, failed holdout'],
['2','H41-B: same layers, two NW donor terminations to one normal receiver','Three-trace convergence motif, not a generic tip union','Moderate–high; more selective, probably lower recall'],
['3','H41-C: same layers, strike switch at family Voronoi boundary','Orientation handover instead of within-family continuation','Moderate; vulnerable to 100 m resolution'],
['4','H41-D: same geometry perturbed 100–300 m','Stable corridors reject mapping-fragment artifacts','High; robustness hypothesis, not new independent geology']])}<p>No numerical DTI gains were invented for ranking. The <a href="{REPO}/blob/6827e43/research/hypotheses.md">preregistration commit</a> predates model implementation. All four can use the acquired inputs; no unavailable external dataset was assumed viable.</p></section>
<section class="section" id="follow-on"><h2>Follow-on hypotheses and the H41-E result</h2><p>Before implementing the next candidate, four untried alternatives were preregistered in <a href="{REPO}/blob/main/research/hypotheses-next.md">the follow-on research plan</a>. The top-ranked H41-E was selected because it addresses a measured kinematic/strike mismatch using existing official fault attributes; no holdout result influenced that ranking.</p>{table(['Rank / ID','Layers and signature','Missing-fault rationale / difference','Cost and expected utility'],[
['1 · tested','H41-E · Qfaults geometry + exact RL/N slip-sense; existing tangent check unchanged','Kinematically screened NW-to-normal off-catalogue corridors; excludes conflicting strike-only labels','Low–moderate; most plausible of this slate, no score gain observed'],
['2','H41-F · normal-fault geometry + single-valued dip direction','Oppositely dipping normal-fault termination/relay motif; differs from cross-family NW-to-normal H41-A','Moderate; sparse attributes may limit recall'],
['3','H41-G · official USGS 3DEP 1 m bare-earth DEM + fault geometry','Fine-scale scarp/curvature edges in unmapped gaps; distinct from 100 m tangent proxy','High; partial tile availability confirmed, full coverage unverified'],
['4','H41-H · Qfaults recency, slip-rate, and mapping-quality fields','Prioritize off-catalogue gaps bounded by recent/high-quality structures; distinct from H41-A geometric proximity alone','Moderate; may bias away from old but real faults']])}<p><strong>Fixed spatial holdout result:</strong> H41-E mean DTI <code>{H41E['means']['H41-E']:.6e}</code> versus H41-A <code>{H41E['means']['H41-A']:.6e}</code>; wins in {H41E['wins_of_four_vs_h41a']}/4 folds. H41-E formed 28 geometric corridors across the fold runs, but emitted zero prediction mass inside all scored fold interiors after orientation/detection gating. Matched-mass controls were vacuous because the candidate mass was zero. It did not beat the current clean in-repo holdout baseline. No new H41-E GeoTIFF or competition submission was produced. The previously delivered unique H41-A GeoTIFF remains available above, explicitly marked research-only.</p><p><strong>Decision: gate remains closed.</strong> No weekly slot was touched. A clean historical-best out-of-fold comparator remains unavailable.</p><p>H41-G source check: the official TNM Access query returned 64 1 m GeoTIFF listings for a sample window within the study raster's geographic bounding box; this does not establish valid-footprint coverage. The sample record includes a direct download URL and official public-domain metadata. This is not proof of full-area coverage or downloaded-byte validation.</p></section>
<section class="section"><h2>Exact implementation</h2><ol><li>Read the official INGENIOUS v2 archive and project full source geometry into EPSG:32611. Retain {A['trace_parts']:,} trace parts from {A['source_ids']} source features inside the footprint. All {A['catalogue_pixels']:,} catalogue pixels lie within 300 m of this geometry.</li><li>Compute length-weighted axial circular mean strike. Assign each trace to the nearer of 135° (NW) and 10° (N/NNE). Keep every trace in the CSV. Only parts ≥600 m, within 30° of their prototype, and axial concentration ≥0.4 can anchor corridors.</li><li>For each NW endpoint, find the nearest N/NNE trace using exact line geometry. Maximum gap 5 km, outward tangent agreement ≥0.5 cosine beyond 200 m. Reject endpoints within 200 m of another NW part and within 300 m of the footprint edge.</li><li>Score distance to the connector with a 500 m Gaussian (truncate at 1,500 m), a 5 km gap taper, and a sinusoidal along-connector taper. Use the maximum over accepted pairs. Suppress all cells within 200 m of the raster catalogue.</li><li>Use only detrended elevation band 12 for local tangent orientation: 1-pixel smoothing, gradient structure tensor smoothed at 2 pixels, coherence ≥0.4, non-flat relief, and an 8-pixel valid-data erosion. This is a broad topographic lineament <em>proxy</em>, not a verified scarp detector.</li><li>Find the nearer family’s rasterized geometry. Multiply corridor score by cos⁸ of the axial tangent mismatch and the detection mask. The factors are already bounded in [0,1]; no label-based normalization or arbitrary display rescaling is applied.</li></ol><div class="method">p(x) = max_corridors C(x) × cos⁸[Δstrike(x, closer family)] × detected(x)<br>C(x) = exp[−d²/(2·500²)] × exp[−gap/5000] × [0.35 + 0.65 sin(πu)]</div><p>All distances are metres; u is the clipped connector projection. All settings were fixed before evaluation. Input geophysical bands other than topography are never used.</p></section>
<section class="section" id="validation"><h2>Blocked validation: a negative result</h2><p>Four-color 20 km spatial blocks use <code>(row//200 + 2*(col//200)) % 4</code>. Remove labels from each held-out region plus a 300 m halo. Remove <em>every full source feature</em> whose full geometry intersects the buffered block polygons; do not create clipping endpoints. Rebuild corridor geometry independently for each fold. Score only interiors eroded by 300 m using the official probabilistic DTI.</p>{table(['Fold','Visible trace parts','Corridors','Held-out mass','Candidate DTI','Geometry-only DTI'],foldrows)}
<p>Mean candidate DTI: <strong>{CV['means']['candidate']:.6e}</strong>. Geometry-only: {CV['means']['geometry_only']:.6e}; matched-mass catalogue density: {CV['means']['catalogue_density']:.6e}; matched-mass topography-only: {CV['means']['topography_only']:.6e}. Mass-matched controls are vacuous in folds where the candidate emits nothing; they do not rescue the result.</p><p>The historical H33 file scores {CV['means']['historical_h33_CONTAMINATED']:.6f} on these catalogue folds, but this is <strong>contaminated and descriptive only</strong>: H33 already used the complete catalogue, including its exclusion mask. Neither this number nor GEMSDOE32’s calibrated mirror is a clean historical-best holdout.</p><div class="notice"><strong>Gate decision: CLOSED.</strong><p>The model relies on nearby visible anchors that disappear under whole-trace blocked withholding. This reveals a support/generalization failure of the current detector–validation combination. It does not prove absence of geological transfer corridors, and it does not justify claiming a high leaderboard score. Do not shrink blocks after seeing this result merely to obtain a better number.</p></div><p><a href="downloads/holdout.json">All fold results, controls and limitations →</a></p></section>
<section class="section"><h2>Does it merely echo catalogue density?</h2>{table(['Diagnostic','Measured result'],[
['Accepted corridors',A['corridors']],['All confidence mass at junctions',f"{100*A['junction_mass_fraction']:.2f}%"],['Junction share of off-catalogue available area',f"{100*A['junction_available_area_fraction']:.3f}%"],['Density-only control mass at junctions',f"{100*A['density_control_junction_mass_fraction']:.2f}%"],['Enrichment relative to density control',f"{A['junction_enrichment_vs_density']:.2f}×"],['Top 5% of nonzero confidence values at junctions',f"{100*A['top5percent_positive_at_junction_fraction']:.2f}%"],['Mass ≤200 m from catalogue','0'],['Enrichment vs NW-only catalogue density',f"{A['population_density_checks']['0']['candidate_enrichment']:.2f}×"],['Enrichment vs N/NNE-only catalogue density',f"{A['population_density_checks']['1']['candidate_enrichment']:.2f}×"],['Sampled Pearson correlation with catalogue density',f"{A['density_correlation']:.3f}"],['Pixel values different from H33',f"{A['comparison']['different_pixel_count']:,}"],['Positive-support Jaccard with H33',f"{A['comparison']['positive_support_jaccard']:.4f}"]])}<p>Junction means within 750 m of the interior 10–90% of an accepted cross-family connector, outside the 200 m catalogue buffer. This checks the hypothesis’s spatial implementation, <strong>not its truth</strong>. The low support overlap with H33 and fresh construction establish novelty versus that examined file; global uniqueness against every unavailable submission cannot be proven.</p></section>
<section class="section"><h2>Scientific corrections and irregularities</h2><ul><li><strong>Astor ≠ Emerson.</strong> Siler, Mayhew &amp; Faulds studied Astor Pass: NW dextral / northerly normal fault interactions. Anderson &amp; Faulds studied Emerson Pass: intersecting oppositely dipping normal faults in a regional displacement-transfer setting. <a href="sources.html">Primary papers and citations</a>.</li><li><strong>Strike ≠ slip sense.</strong> Of 1,501 NW-assigned parts, source attributes report 724 RL, 686 normal, 90 LL, and one unspecified. Of 4,039 N/NNE-assigned parts, 3,129 are normal, 641 RL and 269 LL. These are geometric families, not verified kinematic labels. A forced two-population interpretation misses the ENE sinistral population described by Faulds et al.</li><li><strong>The template mirror is not blank.</strong> It contains 60,988 ones coincident with labels, unlike the public page’s “total fault absence” wording. Only its grid and finite mask are used.</li><li><strong>The repository was empty.</strong> Prior claims of a ready GPU train/inference pipeline and existing holdout did not describe this checkout.</li><li><strong>Acquisition is mixed provenance.</strong> Official vector bytes were directly fetched by Actions; feature and label rasters are pinned owner mirrors, not independently authenticated against the login-walled originals.</li><li><strong>Leaderboard status.</strong> The project archive records a prior public-page observation of 0.3262 on 2026-10-05, above the brief’s reported 0.3195, but neither is asserted as current and neither establishes a filename receipt. The official Terms of Use prohibit automated monitoring, so the source-refresh workflow no longer requests the leaderboard.</li></ul></section>
<section class="section"><h2>Next-session priorities</h2><ol><li><strong>Validation first:</strong> obtain or reconstruct clean historical-best out-of-fold predictions under the same full-source exclusion policy. Preserve the 20 km H41-A/H41-E folds as a fixed audit; do not tune new parameters on their negative result. Preregister any transfer-zone holdout before running it, with geographic grouping and buffers against source-geometry leakage.</li><li><strong>Reassess kinematics:</strong> H41-E's exact `RL`/`N` screen produced zero prediction mass in all four scored interiors. Do not relax codes or thresholds on these same folds. A future kinematic model needs an independent, preregistered test and explicit handling of the archived `SLIPSENSE` schema mismatch.</li><li><strong>Lineament specificity:</strong> investigate 1 m USGS 3DEP terrain scarps rather than broad contour coherence. The official TNM API returned listings in a sample bounding-box window, but full coverage, tile completeness, and alignment to the valid footprint are not established. Do not infer permeable vents from topography alone.</li><li><strong>Subsequent models:</strong> H41-F normal accommodation-zone topology, H41-G 1 m scarp corroboration, and H41-H recency/quality weighting remain proposals only. Rebuild from raw public geometry, report negatives, and use a new locked test for any iteration. The DrivenData leaderboard cannot be automatically polled under its Terms of Use; the score feed states that limitation explicitly.</li></ol><p>These are recommendations, not implemented successes or projected scores. No hidden labels or private test performance are available.</p></section></div>'''
(DOCS/'research.html').write_text(page('Research, hypotheses & validation',research))

sources=[
('S1','DrivenData problem and format',PROBLEM,'Official specification','Fault-discovery target; 300 m triangular kernel; α=.2, β=.8; single float32 band, EPSG:32611, 100 m, null outside.'),
('S2','Official competition rules','https://docs.nlr.gov/docs/fy26osti/96647.pdf','Official, all 7 extracted chunks reviewed','Three weekly submissions; one final choice across two rounds; eligibility, AI disclosure and reproducible solution assets.'),
('S3','INGENIOUS compilation','https://gdr.openei.org/submissions/1391','Official DOE GDR; CC BY 4.0','Ayling et al. (2022), doi:10.15121/1881483. Updated 2023-06-27 v2 fault archive; required attribution retained.'),
('S4','Faulds, Henry & Hinz (2005)','https://nbmg.unr.edu/staff/Faulds/faulds_et_al_geology_paper.pdf','Author institutional PDF','Geology 33:505–508, doi:10.1130/G21274.1. NW dextral systems terminating in N normal faults; also ENE sinistral faults.'),
('S5','Siler, Mayhew & Faulds: Astor Pass','https://www.osti.gov/servlets/purl/1110516','DOE OSTI primary paper','Three-Dimensional Geologic Characterization of Geothermal Systems: Astor Pass, Nevada, USA. Supports fault-intersection controls; not a pixel validation.'),
('S6','Anderson & Faulds: Emerson Pass','https://www.osti.gov/servlets/purl/1110518','DOE OSTI primary paper','Structural Controls of the Emerson Pass Geothermal System, Washoe County, Nevada. Oppositely dipping normal-fault intersections; corrects the brief’s attribution.'),
('S7','Official leaderboard',LEADER,'Official link; user-initiated visit only','The repository records a prior public-page observation of 0.3262 on 2026-10-05. Historical only; not a current score and not tied to a submission file.'),
('S8','Official reference solution','https://github.com/drivendataorg/gems-prize-reference-solution','Organizer repository','Inspected repository tree. Reference neural-network workflow was not copied or claimed to exist here.'),
('S9','Competition data page','https://www.drivendata.org/competitions/306/competition-doe-gems/data/','Official; login required','Verified redirect to login. No DrivenData credentials requested or stored.'),
('S10','Official vector acquisition run',REPO+'/actions/runs/37385329808','Direct acquisition and checksum','6,131,182-byte fault archive; c7b091c9ac8bca140ad89ee6bb2bd63dd3ac12e3013acbfd8373d11c9faee59d.'),
('S11','DrivenData Terms of Use','https://www.drivendata.org/termsofuse/','Official terms','Prohibited Uses state that robots, spiders, or other automatic processes may not access the site for any purpose, including monitoring; manual monitoring without consent is also restricted.'),
('S12','DrivenData robots.txt','https://www.drivendata.org/robots.txt','Official crawler policy','Disallows the leaderboard_partial path. This project does not call the leaderboard or its partial endpoint.'),
('S13','USGS TNM 1 m DEM inventory API','https://tnmaccess.nationalmap.gov/api/v1/products?datasets=Digital%20Elevation%20Model%20(DEM)%201%20meter&bbox=-119.8,39.5,-119.0,40.0&prodFormats=GeoTIFF&max=5','Official API; sample query observed 2026-10-05','Returned 64 matching catalog records for the requested bounding box; metadata includes public download URLs. Sample-window result only; no claim of complete competition-grid coverage.'),
('S14','USGS 1 m DEM collection','https://www.usgs.gov/3d-elevation-program/1-meter-digital-elevation-models-dem','Official USGS dataset description','Describes standard bare-earth, LiDAR-derived 1 m DEMs and states 3DEP products are public domain.'),
('S15','USGS Qfaults slip-style codes','https://pubs.usgs.gov/of/2013/1165/pdf/ofr2013-1165_appendixB.pdf','Official USGS Open-File Report','Defines the style abbreviations RL (right lateral), LL (left lateral), and N (normal); the bundled INGENIOUS field-definition text still differs, so the raw source values are preserved.'),
('S16','USGS ComCat FDSN event API','https://earthquake.usgs.gov/fdsnws/event/1/','Official live API','Browser-refreshed 30-day event context in a study-area bounding box; not fault, geothermal, holdout-label, or score evidence.'),
('S17','USGS State Geologic Map Compilation (SGMC)','https://mrdata.usgs.gov/geology/state/shp/NV.zip','Official USGS, public domain; bytes obtained via digest-verified sibling CI mirror (IRR-11)','Fault traces on the competition grid: 82,151 px in footprint; 65,673 px >200 m and 61,664 px >300 m off the published catalogue; the repository independently reproduced the sibling receipt burn exactly. Upstream endpoint returned 000 from the sandbox (measured 2026-10-06).'),
('S18','GEMSDOE30 sibling repository (score registry + CI external mirrors)','https://github.com/buffedlizard55-lab/GEMSDOE30','Owner-authored sibling; learn-from, never copy','Carries the SGMC-derived grid (sha256 26d142c4…) and the 2 m thermal-probe grid (7ac3cfdf…, 2,467 probes in footprint); used for H42 validation inputs and the uniqueness ledger baseline; both digests verified in-session.')]
related=json.loads((DOCS/'related-sites.json').read_text())['sites']
sources_html=f'''<span class="eyebrow">SOURCE REGISTER / MANUAL REVIEW</span><h1>Evidence you can follow.</h1><p class="lead">Official observations, owner-reported history, and our measured results are separate evidence classes. Links are not a substitute for testing a geological hypothesis.</p>{table(['ID / source','Evidence class','Verified scope'],[[f'<a href="{url}">{id} · {E(title)}</a>',E(kind),E(claim)] for id,title,url,kind,claim in sources])}<section class="section"><h2>Input lineage</h2><p>Official INGENIOUS vector bytes were fetched on a GitHub runner, archive-tested and checksum-pinned. The archive and field definitions are preserved under <code>data/official/</code>. Core rasters came from owner mirrors pinned to commits and SHA-256 in <a href="{REPO}/blob/main/research/input-receipt.json">the input receipt</a>. Hash equality proves mirror integrity, not organizer authentication. No prior prediction raster enters the structural model.</p><p>The <a href="downloads/classified-traces.csv">trace table</a> preserves the original source fields, including slip sense, and distinguishes geometric family from measured kinematics. The <a href="downloads/corridors-utm11.geojson">corridor GeoJSON</a> is explicitly projected UTM11, not RFC 7946 longitude/latitude; use QGIS with EPSG:32611.</p></section><section class="section"><h2>39 related sites, audited</h2><p>All 39 supplied website source files were retrieved through the GitHub contents API and inspected for primary-download, holdout, and score claims. This is a source-level audit, not an exhaustive rerun of every project or verification of every claimed score. Placeholders 40–44 in the brief have no supplied site or result.</p><p><a href="related-sites.json">Complete source hashes and claim excerpts (JSON)</a> · <a href="score-ledger.csv">All submission scores reported in the brief (CSV)</a></p>{table(['Project','Source audit','Evidence class'],[[f'<a href="{r["url"]}">{E(r["repo"])}</a>',E(r['status']),'Owner-authored; no organizer artifact receipt'] for r in related])}</section><section class="section"><h2>Refresh status</h2><p id="source-feed" aria-live="polite">{source_feed_fallback()}<a href="{LEADER}">Open official leaderboard ↗</a> · <a href="https://www.drivendata.org/termsofuse/">Terms of Use ↗</a></p><p><a href="source-feed.json">Timestamped feed JSON</a> · <a href="{REPO}/actions/workflows/site.yml">Source-refresh and Pages run history</a></p><p>The daily workflow checks only non-competition official sources and never fetches the DrivenData site. Failed availability probes are published with their errors and do not become claims about source outage or freshness. This site does not collect logins, use hidden labels, or upload to DrivenData.</p></section>'''
(DOCS/'sources.html').write_text(page('Verified sources & related-site audit',sources_html))

# Preserve all supplied experiment IDs, including unscored entries, in an auditable ledger.
brief=(ROOT/'README.md').read_text().split('<summary>Read the complete original prompt</summary>',1)[1]
rows=[];current=None;seen=set()
for line in brief.splitlines():
    m=re.search(r'https://buffedlizard55-lab.github.io/([^/]+)/',line)
    if m:current=m.group(1)
    match=re.fullmatch(r'([A-Za-z0-9_][A-Za-z0-9_.-]+):\s*(0\.\d+)?',line.strip())
    if match and current:
        key=(current,match.group(1))
        if key not in seen:
            rows.append([current,match.group(1),match.group(2) or '', 'user-reported; not independently artifact-authenticated']);seen.add(key)
with (DOCS/'score-ledger.csv').open('w') as f:
    w=csv.writer(f,lineterminator="\n");w.writerow(['project','submission_id','reported_score','evidence_class']);w.writerows(rows)
# Convenience root: GitHub Pages deploys this file and docs/, not data or the repo.
(ROOT/'index.html').write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=docs/index.html"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GEMSDOE41</title></head><body><a href="docs/index.html">Open GEMSDOE41 — download and research</a></body></html>\n')
print('Built four pages, root redirect, and',len(rows),'score-ledger entries.')
