"""Render a dependency-free static download/research site from measured artifacts."""
import csv
import html
import json
import re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];DOCS=ROOT/'docs'
M=json.loads((DOCS/'downloads/manifest.json').read_text())
A=json.loads((DOCS/'downloads/structural-audit.json').read_text())
CV=json.loads((DOCS/'downloads/holdout.json').read_text())
E=html.escape
REPO='https://github.com/buffedlizard55-lab/GEMSDOE41'
PROBLEM='https://www.drivendata.org/competitions/306/competition-doe-gems/page/967/'
LEADER='https://www.drivendata.org/competitions/306/competition-doe-gems/leaderboard/'
DOWNLOAD='downloads/'+M['filename']

def page(title,body):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="An auditable Walker Lane structural-transfer hypothesis for the DOE GEMS Prize. New GeoTIFF, reproducible evidence, honest validation."><title>{E(title)} · GEMSDOE41</title><link rel="stylesheet" href="style.css"></head><body>
<header><div class="nav"><a class="brand" href="index.html">GEMS<span> / </span>41</a><nav aria-label="Main"><a href="index.html">Overview</a><a href="executive-summary.html">Submission guide</a><a href="research.html">Research &amp; tests</a><a href="sources.html">Evidence</a><a href="{REPO}">Repository ↗</a></nav></div></header><main>{body}</main>
<footer class="footer"><span>Maximize P(Win). Own the Outcome.<br>Reproducible science. No unsupported score promises.</span><span>DOE GEMS research • Built 05 October 2026<br>AI-assisted research and code; no synthetic measurement data.</span></footer><script src="site.js" defer></script></body></html>'''

def download_block():
    return f'''<div class="actions"><a class="button primary" href="{DOWNLOAD}" download>↓ Download new GeoTIFF</a><a href="downloads/format-receipt.json">View format receipt ↗</a></div><p class="fine">One band · float32 · EPSG:32611 · 100 m · 3292 × 3730 · all numeric cells in [0, 1]</p>'''

def table(headers,rows):
    return '<div class="table-wrap"><table><thead><tr>'+''.join('<th>'+x+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(x)+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'

home=f'''<section class="hero"><div><span class="eyebrow">FIELD EXPERIMENT 41 / WALKER LANE</span><h1>Follow the transfer.<br>Test the hypothesis.</h1><p class="lead">A new fault-confidence map built from the space between two structural populations—not from an old submission.</p><span class="pill warn">Research candidate · submission gate closed</span>{download_block()}<p class="fine">Freshly generated artifact. Not organizer-scored. Do not spend a weekly slot on this version.</p></div><div class="map-card"><img src="structural-map.png" alt="Study-area map showing mapped faults in gray and new transfer-corridor confidence in color"><div class="caption">01 / Structural position, not catalogue density. <a href="structural-map.png">Open map ↗</a></div></div></section>
<div class="stats"><div class="stat"><b>{A['trace_parts']:,}</b><span>Trace parts classified by strike</span></div><div class="stat"><b>{A['corridors']}</b><span>Accepted cross-family corridors</span></div><div class="stat"><b>{100*A['top5percent_positive_at_junction_fraction']:.1f}%</b><span>Top-confidence pixels at junctions</span></div><div class="stat"><b>0</b><span>Predicted pixels ≤200 m from catalogue</span></div></div>
<section class="section split"><div><span class="eyebrow">THE RESULT, WITHOUT THE SPIN</span><h2>Valid file.<br>Unproven discovery.</h2><p>The model passes the format, novelty-versus-H33, and junction-concentration checks. It does <strong>not</strong> pass a meaningful generalization gate. Whole-trace withholding leaves almost no supported predictions inside the held-out blocks.</p><a href="research.html#validation">Read the complete failed experiment →</a></div><div class="card"><span class="pill warn">HOLDOUT / DO NOT SUBMIT YET</span><h3>Mean blocked DTI ≈ 0</h3><p>Measured value: <code>{CV['means']['candidate']:.6e}</code>. Only fold 0 has nonzero prediction mass; folds 1–3 have none. Junction concentration is a design check, not independent discovery evidence.</p><p class="fine">The historical H33 raster is not a clean holdout comparator: its construction used the complete catalogue. No claim of beating 0.2778—or the current leader—is justified.</p></div></section>
<section class="section"><span class="eyebrow">TWO GEOMETRIC CRITERIA</span><h2>From fault traces to a falsifiable prediction.</h2><div class="three"><article class="card"><span class="num">01</span><h3>Separate the populations</h3><p>Assign axial strike to NW or N/NNE geometry. Retain every classification, including ambiguous and source-slip-discordant traces.</p></article><article class="card"><span class="num">02</span><h3>Connect genuine endpoints</h3><p>Find the nearest N/NNE receiver within 5 km of an outward-facing NW endpoint. Reject connected fragments and boundary tips.</p></article><article class="card"><span class="num">03</span><h3>Check local orientation</h3><p>Compare a topographic tangent proxy with the geometrically closer population. No new magnetic, gravity, thermal, or conductivity transform.</p></article></div></section>
<section class="section card"><div class="split"><div><span class="eyebrow">DOWNLOAD &amp; REPRODUCE</span><h2>One artifact. A complete audit trail.</h2><p>The static site serves the precomputed, verified model output. It does not claim to train a model in your browser.</p><a href="executive-summary.html">Submission instructions →</a></div><div><p><a href="downloads/classified-traces.csv">Every trace classification (CSV)</a><br><a href="downloads/corridors-utm11.geojson">Transfer corridors (projected GeoJSON)</a><br><a href="downloads/structural-audit.json">Junction &amp; novelty diagnostics</a><br><a href="downloads/holdout.json">Every validation fold</a><br><a href="{REPO}/actions/workflows/reproduce.yml">Rebuild pipeline on GitHub Actions</a></p></div></div></section>
<div class="feed" id="source-feed">Official leaderboard observed 2026-10-05: 0.3262, not the brief’s 0.3195. <a href="{LEADER}">Check official leaderboard ↗</a></div>'''
(DOCS/'index.html').write_text(page('Structural transfer, honestly tested',home))

executive=f'''<div class="prose"><span class="eyebrow">EXECUTIVE SUMMARY / SUBMISSION GUIDE</span><h1>Your GeoTIFF, ready to inspect.</h1><p class="lead">The file has been generated and independently re-opened. Download it directly—no conversion, editing, or model training is required.</p>{download_block()}<div class="notice"><strong>Do not submit this candidate yet.</strong><p>The blocked validation result is effectively zero and a clean historical-best comparison is unavailable. Format-valid does not mean scientifically validated or competitive. No weekly slot has been spent.</p></div>
<h2>Artifact identity</h2><p><strong>Filename</strong><br><code>{M['filename']}</code></p><p><strong>Unique submission name</strong><br><code>{M['submission_name']}</code></p><p><strong>Short note ({len(M['note'])} characters)</strong></p><div class="copybox"><code id="submission-note">{E(M['note'])}</code><button class="copy" data-copy="submission-note" type="button">Copy note</button></div><p class="fine">SHA-256: <code>{M['format']['sha256']}</code></p>
<section class="section"><h2>When a future candidate clears the gate</h2><ol><li>Review its <strong>clean, spatially blocked comparison</strong> against the current best. Require an improvement before spending one of the three weekly slots.</li><li>Download the single <code>.tif</code> using the button above. Do not upload the map PNG, HTML page, audit JSON, or a renamed document.</li><li>Sign in to <a href="https://www.drivendata.org/competitions/306/competition-doe-gems/">DrivenData’s GEMS competition</a>, confirm eligibility and accept the official rules using your own account.</li><li>Open <strong>New submission</strong>. Under <strong>File to submit</strong>, choose the downloaded GeoTIFF. Use the unique name in your internal tracker and paste the short note into <strong>Note (optional)</strong>.</li><li>Submit only after the gate passes. Wait for the portal’s validation and score. Record the exact file hash, submission ID, note, and organizer-reported score. A local validator cannot guarantee portal acceptance.</li><li>Select one final submission for both prize rounds by the official deadline. Disclose AI assistance in the required narrative; eligibility and certifications must be completed by the participant.</li></ol><p>These steps follow the <a href="{PROBLEM}#submission-format">format specification</a> and <a href="https://docs.nlr.gov/docs/fy26osti/96647.pdf">official rules, §§3.2–3.5</a>.</p></section>
<section class="section"><h2>Why this file avoids the range error</h2><p>Every one of its 12,279,160 stored values is finite, with minimum 0 and maximum {M['format']['max']:.6f}. There is no negative sentinel or NaN-valued nodata tag. Outside-footprint cells contain numeric zero <em>and</em> are null through an internal GeoTIFF mask matching the template. This reconciles the published null-outside requirement with safe numerical values.</p><p>The exact cause of your earlier portal error is unknown without the rejected bytes. Out-of-range sentinel values are one possible cause; NaN alone is not proven to be the cause. We verified the current file rather than guessing about the old one.</p></section>
<section class="section"><h2>Rebuild rather than copy</h2><pre><code>bash scripts/download_competition_data.sh
.venv/bin/python scripts/prepare_data.py
.venv/bin/python scripts/run_pipeline.py
.venv/bin/python scripts/build_site.py</code></pre><p><a href="{REPO}/actions/workflows/reproduce.yml">Run the reproducibility workflow</a> or use the setup commands in the README. The geometry-only model is CPU-based; it does not require a GPU. Reproducing identical inputs intentionally gives the same content-addressed artifact, not an artificial “new” file made by renaming it.</p></section></div>'''
(DOCS/'executive-summary.html').write_text(page('Executive summary & submission',executive))

foldrows=[[f['fold'],f['anchor_parts'],f['corridors'],f"{f['prediction_mass']:.8f}",f"{f['metrics']['candidate']['dti']:.6e}",f"{f['metrics']['geometry_only']['dti']:.6e}"] for f in CV['folds']]
research=f'''<div class="prose"><span class="eyebrow">RESEARCH NOTE / H41-A</span><h1>A structural hypothesis.<br>Not a score promise.</h1><p class="lead">The target is missing geological faults indicative of geothermal resources—not verified geothermal vents, reservoirs, or drill-ready prospects.</p>
<section class="section"><h2>Why H33’s reported 0.2778 is plausible</h2><p><strong>Measured artifact and source-code evidence:</strong> GEMSDOE32 H33-2-B2 contains 37,654 binary dots. Its published method removes 2,545 pixels (6.33%) within 200 m of the catalogue from a 40,199-dot base reported at 0.2708. This is a precision/budget modification to an existing detector, not a new geological detector. <a href="https://buffedlizard55-lab.github.io/GEMSDOE32/docs/index.html">Inspect the source site</a>.</p><p><strong>Mathematical explanation:</strong> the <a href="{PROBLEM}#performance-metric">official metric</a> rewards the maximum kernel-weighted prediction at each truth pixel; nearby redundant dots can add false-positive mass without adding coverage. Let T be weighted true positives, S prediction mass, M the sum of prediction times nearest-truth kernel, and G the number of truth pixels:</p><div class="method">DTI = T / [0.2(T + S − M) + 0.8G]</div><p>If removed pixels contribute little unique coverage or truth proximity, reducing S improves this ratio. The hidden test faults are explicitly outside the existing catalogue, which makes near-catalogue pruning a reasonable initial-round hypothesis. It can still remove real adjacent new faults and may sacrifice final-round coverage.</p><p><strong>Not established:</strong> the hidden labels and organizer artifact receipt are unavailable. The 0.2778 filename-to-score link is user-reported; the official leaderboard displays that score for a participant, not that file. H33’s own page still says unscored. Its “live mirror” uses SGMC proxy truth and prevalence calibration; it is not an independent held-out expert dataset and cannot validate a new geometry-only regime.</p><p><strong>Can we score higher?</strong> Possibly, but neither prior scores nor this experiment establish that we can. A 0.2778→0.3262 change would be a 17.4% increase in DTI; it is not automatically a 17.4% increase in recall. Thresholds and synthetic truth models cannot manufacture new structural evidence.</p></section>
<section class="section"><h2>Four candidates, ranked before implementation</h2>{table(['Rank','Hypothesis and layers','Missing-fault mechanism / novelty','Cost & expected utility'],[
['1 · implemented','H41-A: official faults + detrended elevation tangent','Unlike-family endpoint→nearest-receiver corridors; new field rather than H33 pruning','Moderate; highest qualitative plausibility, failed holdout'],
['2','H41-B: same layers, two NW donor terminations to one normal receiver','Three-trace convergence motif, not a generic tip union','Moderate–high; more selective, probably lower recall'],
['3','H41-C: same layers, strike switch at family Voronoi boundary','Orientation handover instead of within-family continuation','Moderate; vulnerable to 100 m resolution'],
['4','H41-D: same geometry perturbed 100–300 m','Stable corridors reject mapping-fragment artifacts','High; robustness hypothesis, not new independent geology']])}<p>No numerical DTI gains were invented for ranking. The <a href="{REPO}/blob/6827e43/research/hypotheses.md">preregistration commit</a> predates model implementation. All four can use the acquired inputs; no unavailable external dataset was assumed viable.</p></section>
<section class="section"><h2>Exact implementation</h2><ol><li>Read the official INGENIOUS v2 archive and project full source geometry into EPSG:32611. Retain {A['trace_parts']:,} trace parts from {A['source_ids']} source features inside the footprint. All {A['catalogue_pixels']:,} catalogue pixels lie within 300 m of this geometry.</li><li>Compute length-weighted axial circular mean strike. Assign each trace to the nearer of 135° (NW) and 10° (N/NNE). Keep every trace in the CSV. Only parts ≥600 m, within 30° of their prototype, and axial concentration ≥0.4 can anchor corridors.</li><li>For each NW endpoint, find the nearest N/NNE trace using exact line geometry. Maximum gap 5 km, outward tangent agreement ≥0.5 cosine beyond 200 m. Reject endpoints within 200 m of another NW part and within 300 m of the footprint edge.</li><li>Score distance to the connector with a 500 m Gaussian (truncate at 1,500 m), a 5 km gap taper, and a sinusoidal along-connector taper. Use the maximum over accepted pairs. Suppress all cells within 200 m of the raster catalogue.</li><li>Use only detrended elevation band 12 for local tangent orientation: 1-pixel smoothing, gradient structure tensor smoothed at 2 pixels, coherence ≥0.4, non-flat relief, and an 8-pixel valid-data erosion. This is a broad topographic lineament <em>proxy</em>, not a verified scarp detector.</li><li>Find the nearer family’s rasterized geometry. Multiply corridor score by cos⁸ of the axial tangent mismatch and the detection mask. The factors are already bounded in [0,1]; no label-based normalization or arbitrary display rescaling is applied.</li></ol><div class="method">p(x) = max_corridors C(x) × cos⁸[Δstrike(x, closer family)] × detected(x)<br>C(x) = exp[−d²/(2·500²)] × exp[−gap/5000] × [0.35 + 0.65 sin(πu)]</div><p>All distances are metres; u is the clipped connector projection. All settings were fixed before evaluation. Input geophysical bands other than topography are never used.</p></section>
<section class="section" id="validation"><h2>Blocked validation: a negative result</h2><p>Four-color 20 km spatial blocks use <code>(row//200 + 2*(col//200)) % 4</code>. Remove labels from each held-out region plus a 300 m halo. Remove <em>every full source feature</em> whose full geometry intersects the buffered block polygons; do not create clipping endpoints. Rebuild corridor geometry independently for each fold. Score only interiors eroded by 300 m using the official probabilistic DTI.</p>{table(['Fold','Visible trace parts','Corridors','Held-out mass','Candidate DTI','Geometry-only DTI'],foldrows)}
<p>Mean candidate DTI: <strong>{CV['means']['candidate']:.6e}</strong>. Geometry-only: {CV['means']['geometry_only']:.6e}; matched-mass catalogue density: {CV['means']['catalogue_density']:.6e}; matched-mass topography-only: {CV['means']['topography_only']:.6e}. Mass-matched controls are vacuous in folds where the candidate emits nothing; they do not rescue the result.</p><p>The historical H33 file scores {CV['means']['historical_h33_CONTAMINATED']:.6f} on these catalogue folds, but this is <strong>contaminated and descriptive only</strong>: H33 already used the complete catalogue, including its exclusion mask. Neither this number nor GEMSDOE32’s calibrated mirror is a clean historical-best holdout.</p><div class="notice"><strong>Gate decision: CLOSED.</strong><p>The model relies on nearby visible anchors that disappear under whole-trace blocked withholding. This reveals a support/generalization failure of the current detector–validation combination. It does not prove absence of geological transfer corridors, and it does not justify claiming a high leaderboard score. Do not shrink blocks after seeing this result merely to obtain a better number.</p></div><p><a href="downloads/holdout.json">All fold results, controls and limitations →</a></p></section>
<section class="section"><h2>Does it merely echo catalogue density?</h2>{table(['Diagnostic','Measured result'],[
['Accepted corridors',A['corridors']],['All confidence mass at junctions',f"{100*A['junction_mass_fraction']:.2f}%"],['Junction share of off-catalogue available area',f"{100*A['junction_available_area_fraction']:.3f}%"],['Density-only control mass at junctions',f"{100*A['density_control_junction_mass_fraction']:.2f}%"],['Enrichment relative to density control',f"{A['junction_enrichment_vs_density']:.2f}×"],['Top 5% of nonzero confidence values at junctions',f"{100*A['top5percent_positive_at_junction_fraction']:.2f}%"],['Mass ≤200 m from catalogue','0'],['Enrichment vs NW-only catalogue density',f"{A['population_density_checks']['0']['candidate_enrichment']:.2f}×"],['Enrichment vs N/NNE-only catalogue density',f"{A['population_density_checks']['1']['candidate_enrichment']:.2f}×"],['Sampled Pearson correlation with catalogue density',f"{A['density_correlation']:.3f}"],['Pixel values different from H33',f"{A['comparison']['different_pixel_count']:,}"],['Positive-support Jaccard with H33',f"{A['comparison']['positive_support_jaccard']:.4f}"]])}<p>Junction means within 750 m of the interior 10–90% of an accepted cross-family connector, outside the 200 m catalogue buffer. This checks the hypothesis’s spatial implementation, <strong>not its truth</strong>. The low support overlap with H33 and fresh construction establish novelty versus that examined file; global uniqueness against every unavailable submission cannot be proven.</p></section>
<section class="section"><h2>Scientific corrections and irregularities</h2><ul><li><strong>Astor ≠ Emerson.</strong> Siler, Mayhew &amp; Faulds studied Astor Pass: NW dextral / northerly normal fault interactions. Anderson &amp; Faulds studied Emerson Pass: intersecting oppositely dipping normal faults in a regional displacement-transfer setting. <a href="sources.html">Primary papers and citations</a>.</li><li><strong>Strike ≠ slip sense.</strong> Of 1,501 NW-assigned parts, source attributes report 724 RL, 686 normal, 90 LL, and one unspecified. Of 4,039 N/NNE-assigned parts, 3,129 are normal, 641 RL and 269 LL. These are geometric families, not verified kinematic labels. A forced two-population interpretation misses the ENE sinistral population described by Faulds et al.</li><li><strong>The template mirror is not blank.</strong> It contains 60,988 ones coincident with labels, unlike the public page’s “total fault absence” wording. Only its grid and finite mask are used.</li><li><strong>The repository was empty.</strong> Prior claims of a ready GPU train/inference pipeline and existing holdout did not describe this checkout.</li><li><strong>Acquisition is mixed provenance.</strong> Official vector bytes were directly fetched by Actions; feature and label rasters are pinned owner mirrors, not independently authenticated against the login-walled originals.</li><li><strong>Leaderboard correction.</strong> The official page showed 0.3262 on 2026-10-05, above the brief’s stale 0.3195. Owner scores and publicly displayed participant scores do not establish a filename receipt.</li></ul></section>
<section class="section"><h2>Next-session priorities</h2><ol><li><strong>Validation first:</strong> obtain or reconstruct clean historical-best out-of-fold predictions with the same whole-source exclusion policy. Keep the untouched 20 km audit set; preregister a separate transfer-zone test where donor and receiver faults remain visible and an intervening trace is withheld, with geographic grouping and a buffer preventing target leakage.</li><li><strong>Kinematic quality:</strong> test the source slip-sense attributes already acquired to resolve normal NW traces and ENE sinistral faults. Compare strike-only vs kinematics-constrained anchors on the new preregistered test—not the exhausted audit folds.</li><li><strong>Lineament specificity:</strong> use independent terrain scarps rather than broad contour coherence. USGS 3DEP high-resolution terrain is an official possible source; tile-level acquisition and license/provenance must be verified before treating it as available. Do not infer permeable vents from topography alone.</li><li><strong>Only then:</strong> test the H41-B convergence motif and H41-D topology stability. Rebuild every field from raw geometry, compare at honest prediction budgets, retain negative results, and spend a weekly slot only after a valid gate passes.</li></ol><p>These are recommendations, not implemented successes or projected scores. No hidden labels or private test performance are available.</p></section></div>'''
(DOCS/'research.html').write_text(page('Research, hypotheses & validation',research))

sources=[
('S1','DrivenData problem and format',PROBLEM,'Official specification','Fault-discovery target; 300 m triangular kernel; α=.2, β=.8; single float32 band, EPSG:32611, 100 m, null outside.'),
('S2','Official competition rules','https://docs.nlr.gov/docs/fy26osti/96647.pdf','Official, all 7 extracted chunks reviewed','Three weekly submissions; one final choice across two rounds; eligibility, AI disclosure and reproducible solution assets.'),
('S3','INGENIOUS compilation','https://gdr.openei.org/submissions/1391','Official DOE GDR; CC BY 4.0','Ayling et al. (2022), doi:10.15121/1881483. Updated 2023-06-27 v2 fault archive; required attribution retained.'),
('S4','Faulds, Henry & Hinz (2005)','https://nbmg.unr.edu/staff/Faulds/faulds_et_al_geology_paper.pdf','Author institutional PDF','Geology 33:505–508, doi:10.1130/G21274.1. NW dextral systems terminating in N normal faults; also ENE sinistral faults.'),
('S5','Siler, Mayhew & Faulds: Astor Pass','https://www.osti.gov/servlets/purl/1110516','DOE OSTI primary paper','Three-Dimensional Geologic Characterization of Geothermal Systems: Astor Pass, Nevada, USA. Supports fault-intersection controls; not a pixel validation.'),
('S6','Anderson & Faulds: Emerson Pass','https://www.osti.gov/servlets/purl/1110518','DOE OSTI primary paper','Structural Controls of the Emerson Pass Geothermal System, Washoe County, Nevada. Oppositely dipping normal-fault intersections; corrects the brief’s attribution.'),
('S7','Official leaderboard',LEADER,'Official observed snapshot','0.3262 leader on 2026-10-05; 0.2778 participant entry observed, no public artifact-to-score receipt.'),
('S8','Official reference solution','https://github.com/drivendataorg/gems-prize-reference-solution','Organizer repository','Inspected repository tree. Reference neural-network workflow was not copied or claimed to exist here.'),
('S9','Competition data page','https://www.drivendata.org/competitions/306/competition-doe-gems/data/','Official; login required','Verified redirect to login. No DrivenData credentials requested or stored.'),
('S10','Official vector acquisition run',REPO+'/actions/runs/37385329808','Direct acquisition and checksum','6,131,182-byte fault archive; c7b091c9ac8bca140ad89ee6bb2bd63dd3ac12e3013acbfd8373d11c9faee59d.')]
related=json.loads((DOCS/'related-sites.json').read_text())['sites']
sources_html=f'''<span class="eyebrow">SOURCE REGISTER / MANUAL REVIEW</span><h1>Evidence you can follow.</h1><p class="lead">Official observations, owner-reported history, and our measured results are separate evidence classes. Links are not a substitute for testing a geological hypothesis.</p>{table(['ID / source','Evidence class','Verified scope'],[[f'<a href="{url}">{id} · {E(title)}</a>',E(kind),E(claim)] for id,title,url,kind,claim in sources])}<section class="section"><h2>Input lineage</h2><p>Official INGENIOUS vector bytes were fetched on a GitHub runner, archive-tested and checksum-pinned. The archive and field definitions are preserved under <code>data/official/</code>. Core rasters came from owner mirrors pinned to commits and SHA-256 in <a href="{REPO}/blob/arena/5d5d8cc8-gemsdoe41/research/input-receipt.json">the input receipt</a>. Hash equality proves mirror integrity, not organizer authentication. No prior prediction raster enters the structural model.</p><p>The <a href="downloads/classified-traces.csv">trace table</a> preserves the original source fields, including slip sense, and distinguishes geometric family from measured kinematics. The <a href="downloads/corridors-utm11.geojson">corridor GeoJSON</a> is explicitly projected UTM11, not RFC 7946 longitude/latitude; use QGIS with EPSG:32611.</p></section><section class="section"><h2>39 related sites, audited</h2><p>All 39 supplied website source files were retrieved through the GitHub contents API and inspected for primary-download, holdout, and score claims. This is a source-level audit, not an exhaustive rerun of every project or verification of every claimed score. Placeholders 40–44 in the brief have no supplied site or result.</p><p><a href="related-sites.json">Complete source hashes and claim excerpts (JSON)</a> · <a href="score-ledger.csv">All submission scores reported in the brief (CSV)</a></p>{table(['Project','Source audit','Evidence class'],[[f'<a href="{r["url"]}">{E(r["repo"])}</a>',E(r['status']),'Owner-authored; no organizer artifact receipt'] for r in related])}</section><section class="section"><h2>Refresh status</h2><p id="source-feed">Checked via research tools on 2026-10-05. Daily public-source checks run through GitHub Actions after merge.</p><p><a href="source-feed.json">Timestamped feed JSON</a> · <a href="{REPO}/actions/workflows/site.yml">Source-refresh and Pages run history</a></p><p>Fetch failures are published as errors and no score is invented. Source availability and scientific truth are different checks. This site does not collect logins, use hidden labels, or upload to DrivenData.</p></section>'''
(DOCS/'sources.html').write_text(page('Verified sources & related-site audit',sources_html))

# Preserve all supplied experiment IDs, including unscored entries, in an auditable ledger.
brief=(ROOT/'README.md').read_text().split('<summary>Read the complete original prompt</summary>',1)[1]
rows=[];current=None;seen=set()
for line in brief.splitlines():
    m=re.search(r'https://buffedlizard55-lab.github.io/([^/]+)/',line)
    if m:current=m.group(1)
    match=re.fullmatch(r'([A-Za-z0-9_][A-Za-z0-9_.-]+):\s*(0\.\d+)?',line.strip())
    if match and current:
        key=(current,match.group(1))
        if key not in seen:
            rows.append([current,match.group(1),match.group(2) or '', 'user-reported; not independently artifact-authenticated']);seen.add(key)
with (DOCS/'score-ledger.csv').open('w') as f:
    w=csv.writer(f);w.writerow(['project','submission_id','reported_score','evidence_class']);w.writerows(rows)
# Convenience root: GitHub Pages deploys this file and docs/, not data or the repo.
(ROOT/'index.html').write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=docs/index.html"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GEMSDOE41</title></head><body><a href="docs/index.html">Open GEMSDOE41 — download and research</a></body></html>\n')
print('Built four pages, root redirect, and',len(rows),'score-ledger entries.')
